//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Broker.Contracts.Data
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://schemas.datacontract.org/2004/07/Broker.Contracts.Data")]
    public partial class Message : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string TextField;
        
        private string TopicField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text
        {
            get
            {
                return this.TextField;
            }
            set
            {
                this.TextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Topic
        {
            get
            {
                return this.TopicField;
            }
            set
            {
                this.TopicField = value;
            }
        }
    }
}
namespace Broker.Contracts.Faults
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PublicationFault", Namespace="http://schemas.datacontract.org/2004/07/Broker.Contracts.Faults")]
    public partial class PublicationFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DescriptionField;
        
        private string TopicField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Topic
        {
            get
            {
                return this.TopicField;
            }
            set
            {
                this.TopicField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IPublisherService")]
public interface IPublisherService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublisherService/Publish", ReplyAction="http://tempuri.org/IPublisherService/PublishResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(Broker.Contracts.Faults.PublicationFault), Action="http://tempuri.org/IPublisherService/PublishPublicationFaultFault", Name="PublicationFault", Namespace="http://schemas.datacontract.org/2004/07/Broker.Contracts.Faults")]
    void Publish(Broker.Contracts.Data.Message message);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublisherService/Publish", ReplyAction="http://tempuri.org/IPublisherService/PublishResponse")]
    System.Threading.Tasks.Task PublishAsync(Broker.Contracts.Data.Message message);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IPublisherServiceChannel : IPublisherService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class PublisherServiceClient : System.ServiceModel.ClientBase<IPublisherService>, IPublisherService
{
    
    public PublisherServiceClient()
    {
    }
    
    public PublisherServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public PublisherServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public PublisherServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public PublisherServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void Publish(Broker.Contracts.Data.Message message)
    {
        base.Channel.Publish(message);
    }
    
    public System.Threading.Tasks.Task PublishAsync(Broker.Contracts.Data.Message message)
    {
        return base.Channel.PublishAsync(message);
    }
}
