//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Broker.Contracts.Data
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubscriptionResponse", Namespace="http://schemas.datacontract.org/2004/07/Broker.Contracts.Data")]
    public partial class SubscriptionResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string QueuePathField;
        
        private string TopicNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QueuePath
        {
            get
            {
                return this.QueuePathField;
            }
            set
            {
                this.QueuePathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TopicName
        {
            get
            {
                return this.TopicNameField;
            }
            set
            {
                this.TopicNameField = value;
            }
        }
    }
}
namespace Broker.Contracts.Faults
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubscriptionFault", Namespace="http://schemas.datacontract.org/2004/07/Broker.Contracts.Faults")]
    public partial class SubscriptionFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DescriptionField;
        
        private string TopicField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Topic
        {
            get
            {
                return this.TopicField;
            }
            set
            {
                this.TopicField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ISubscriberService")]
public interface ISubscriberService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubscriberService/Subscribe", ReplyAction="http://tempuri.org/ISubscriberService/SubscribeResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(Broker.Contracts.Faults.SubscriptionFault), Action="http://tempuri.org/ISubscriberService/SubscribeSubscriptionFaultFault", Name="SubscriptionFault", Namespace="http://schemas.datacontract.org/2004/07/Broker.Contracts.Faults")]
    Broker.Contracts.Data.SubscriptionResponse Subscribe(string topicName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubscriberService/Subscribe", ReplyAction="http://tempuri.org/ISubscriberService/SubscribeResponse")]
    System.Threading.Tasks.Task<Broker.Contracts.Data.SubscriptionResponse> SubscribeAsync(string topicName);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ISubscriberServiceChannel : ISubscriberService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class SubscriberServiceClient : System.ServiceModel.ClientBase<ISubscriberService>, ISubscriberService
{
    
    public SubscriberServiceClient()
    {
    }
    
    public SubscriberServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public SubscriberServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SubscriberServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SubscriberServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public Broker.Contracts.Data.SubscriptionResponse Subscribe(string topicName)
    {
        return base.Channel.Subscribe(topicName);
    }
    
    public System.Threading.Tasks.Task<Broker.Contracts.Data.SubscriptionResponse> SubscribeAsync(string topicName)
    {
        return base.Channel.SubscribeAsync(topicName);
    }
}
