//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Broker.Contracts.Data
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TopicItem", Namespace="http://schemas.datacontract.org/2004/07/Broker.Contracts.Data")]
    public partial class TopicItem : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string NameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ITopicService")]
public interface ITopicService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITopicService/GetTopicList", ReplyAction="http://tempuri.org/ITopicService/GetTopicListResponse")]
    Broker.Contracts.Data.TopicItem[] GetTopicList();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITopicService/GetTopicList", ReplyAction="http://tempuri.org/ITopicService/GetTopicListResponse")]
    System.Threading.Tasks.Task<Broker.Contracts.Data.TopicItem[]> GetTopicListAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ITopicServiceChannel : ITopicService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class TopicServiceClient : System.ServiceModel.ClientBase<ITopicService>, ITopicService
{
    
    public TopicServiceClient()
    {
    }
    
    public TopicServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public TopicServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TopicServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TopicServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public Broker.Contracts.Data.TopicItem[] GetTopicList()
    {
        return base.Channel.GetTopicList();
    }
    
    public System.Threading.Tasks.Task<Broker.Contracts.Data.TopicItem[]> GetTopicListAsync()
    {
        return base.Channel.GetTopicListAsync();
    }
}
