//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Broker.Client.SubscriberService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubscriptionResponse", Namespace="http://schemas.datacontract.org/2004/07/Broker.Contracts.Data")]
    [System.SerializableAttribute()]
    public partial class SubscriptionResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QueuePathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TopicNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QueuePath {
            get {
                return this.QueuePathField;
            }
            set {
                if ((object.ReferenceEquals(this.QueuePathField, value) != true)) {
                    this.QueuePathField = value;
                    this.RaisePropertyChanged("QueuePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TopicName {
            get {
                return this.TopicNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TopicNameField, value) != true)) {
                    this.TopicNameField = value;
                    this.RaisePropertyChanged("TopicName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubscriptionFault", Namespace="http://schemas.datacontract.org/2004/07/Broker.Contracts.Faults")]
    [System.SerializableAttribute()]
    public partial class SubscriptionFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TopicField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Topic {
            get {
                return this.TopicField;
            }
            set {
                if ((object.ReferenceEquals(this.TopicField, value) != true)) {
                    this.TopicField = value;
                    this.RaisePropertyChanged("Topic");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SubscriberService.ISubscriberService")]
    public interface ISubscriberService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubscriberService/Subscribe", ReplyAction="http://tempuri.org/ISubscriberService/SubscribeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Broker.Client.SubscriberService.SubscriptionFault), Action="http://tempuri.org/ISubscriberService/SubscribeSubscriptionFaultFault", Name="SubscriptionFault", Namespace="http://schemas.datacontract.org/2004/07/Broker.Contracts.Faults")]
        Broker.Client.SubscriberService.SubscriptionResponse Subscribe(string topicName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubscriberService/Subscribe", ReplyAction="http://tempuri.org/ISubscriberService/SubscribeResponse")]
        System.Threading.Tasks.Task<Broker.Client.SubscriberService.SubscriptionResponse> SubscribeAsync(string topicName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISubscriberServiceChannel : Broker.Client.SubscriberService.ISubscriberService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SubscriberServiceClient : System.ServiceModel.ClientBase<Broker.Client.SubscriberService.ISubscriberService>, Broker.Client.SubscriberService.ISubscriberService {
        
        public SubscriberServiceClient() {
        }
        
        public SubscriberServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SubscriberServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubscriberServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubscriberServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Broker.Client.SubscriberService.SubscriptionResponse Subscribe(string topicName) {
            return base.Channel.Subscribe(topicName);
        }
        
        public System.Threading.Tasks.Task<Broker.Client.SubscriberService.SubscriptionResponse> SubscribeAsync(string topicName) {
            return base.Channel.SubscribeAsync(topicName);
        }
    }
}
