//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Broker.Client.TopicService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TopicItem", Namespace="http://schemas.datacontract.org/2004/07/Broker.Contracts.Data")]
    [System.SerializableAttribute()]
    public partial class TopicItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TopicService.ITopicService")]
    public interface ITopicService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITopicService/GetTopicList", ReplyAction="http://tempuri.org/ITopicService/GetTopicListResponse")]
        Broker.Client.TopicService.TopicItem[] GetTopicList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITopicService/GetTopicList", ReplyAction="http://tempuri.org/ITopicService/GetTopicListResponse")]
        System.Threading.Tasks.Task<Broker.Client.TopicService.TopicItem[]> GetTopicListAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITopicServiceChannel : Broker.Client.TopicService.ITopicService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TopicServiceClient : System.ServiceModel.ClientBase<Broker.Client.TopicService.ITopicService>, Broker.Client.TopicService.ITopicService {
        
        public TopicServiceClient() {
        }
        
        public TopicServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TopicServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TopicServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TopicServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Broker.Client.TopicService.TopicItem[] GetTopicList() {
            return base.Channel.GetTopicList();
        }
        
        public System.Threading.Tasks.Task<Broker.Client.TopicService.TopicItem[]> GetTopicListAsync() {
            return base.Channel.GetTopicListAsync();
        }
    }
}
